# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
# marketing:
#   seo:
#     site_type: Person
#     local_business_type: ''
#     org_name: ''
#     description: 'The highly-customizable Hugo Academic theme powered by Hugo Blox Builder. Easily create your personal academic website.'
#     twitter: 'GetResearchDev'
#   analytics:
#     google_analytics: ''
#     baidu_tongji: ''
#     plausible: ''
#     fathom: ''
#     pirsch: ''
#   verification:
#     google: ''
#     baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Weiyuan Liang | Thermoacoustic and flow physics"
      filename: ''

# Site footer
footer:
  copyright:
    notice: '© {year} W.Liang. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: false
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: ture
  privacy_pack:
    enable: ture
  comment:
    # Choose a provider: giscus, disqus, commento, or '' to disable commenting
    provider: giscus
    giscus:
      repo: 'taco-bro/academic-website'
      repo_id: 'R_kgDOPda-dw'
      category: 'General'
      category_id: 'DIC_kwDOPda-d84CuPf4'
      theme: preferred_color_scheme
      language_code: en
      mapping: pathname
    disqus:
      # Paste the shortname from your Disqus dashboard.
      shortname: ''
      # Show comment count in page header? (true/false)
      show_count: true
    commento:
      # If you self-host Commento, enter your custom Commento URL here.
      url: ''

# Dara Analytic
marketing:
  analytics:
    microsoft_clarity: 'svm81ytor4'
